extartingurl1

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -115,6 +115,17 @@ jobs:
             AZURE_SUBSCRIPTION_ID
             AZURE_ENV_NAME
             AZURE_LOCATION
+      - name: Extract Web URLs from .env
+        run: |
+          echo "Extracting frontend/admin URLs from .env"
+          if [ -f .env ]; then
+            source .env
+            echo "FRONTEND_WEBSITE_URL=$FRONTEND_WEBSITE_URL" >> $GITHUB_ENV
+            echo "ADMIN_WEBSITE_URL=$ADMIN_WEBSITE_URL" >> $GITHUB_ENV
+          else
+            echo ".env file not found"
+            exit 1
+          fi
 
   cleanup:
     runs-on: ubuntu-latest
@@ -147,17 +158,7 @@ jobs:
             AZURE_SUBSCRIPTION_ID
             AZURE_ENV_NAME
             AZURE_LOCATION
-      - name: Extract Web URLs from .env
-        run: |
-          echo "Extracting frontend/admin URLs from .env"
-          if [ -f .env ]; then
-            source .env
-            echo "FRONTEND_WEBSITE_URL=$FRONTEND_WEBSITE_URL" >> $GITHUB_ENV
-            echo "ADMIN_WEBSITE_URL=$ADMIN_WEBSITE_URL" >> $GITHUB_ENV
-          else
-            echo ".env file not found"
-            exit 1
-          fi
+
 
       - name: Send Notification on Failure
         if: failure()
