removed auth and updated prebulit step

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -106,7 +106,21 @@ jobs:
           imageName: ghcr.io/azure-samples/chat-with-your-data-solution-accelerator
           cacheFrom: ghcr.io/azure-samples/chat-with-your-data-solution-accelerator
           imageTag: ${{ env.imageTag }}
-          runCmd: export optional_args="./code/tests" && make ci && make deploy
+          runCmd: |
+            export optional_args="./code/tests"
+            make ci && make deploy
+
+            # Export the .env variables to GitHub Actions environment
+            if [ -f .env ]; then
+              source .env
+              echo "FRONTEND_WEBSITE_URL=$FRONTEND_WEBSITE_URL" >> $GITHUB_ENV
+              echo "ADMIN_WEBSITE_URL=$ADMIN_WEBSITE_URL" >> $GITHUB_ENV
+              echo "ENFORCE_AUTH=$ENFORCE_AUTH" >> $GITHUB_ENV
+            else
+              echo ".env file not found" >&2
+              exit 1
+            fi
+
           refFilterForPush: refs/heads/${{ github.event_name == 'schedule' && 'main' || github.ref_name }}
           env: |
             AZURE_CLIENT_ID
@@ -115,17 +129,8 @@ jobs:
             AZURE_SUBSCRIPTION_ID
             AZURE_ENV_NAME
             AZURE_LOCATION
-      - name: Extract Web URLs from .env
-        run: |
-          echo "Extracting frontend/admin URLs from .env"
-          if [ -f .env ]; then
-            source .env
-            echo "FRONTEND_WEBSITE_URL=$FRONTEND_WEBSITE_URL" >> $GITHUB_ENV
-            echo "ADMIN_WEBSITE_URL=$ADMIN_WEBSITE_URL" >> $GITHUB_ENV
-          else
-            echo ".env file not found"
-            exit 1
-          fi
+            ENFORCE_AUTH=false
+
 
   cleanup:
     runs-on: ubuntu-latest
